# Generated by Django 3.2.7 on 2021-10-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='text_id',
            field=models.IntegerField(default=1),
        ),
    ]
